// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[room].tsx";
import * as $1 from "./routes/api/connect.ts";
import * as $2 from "./routes/api/send.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/AddRoom.tsx";
import * as $$1 from "./islands/Chat.tsx";

const manifest = {
  routes: {
    "./routes/[room].tsx": $0,
    "./routes/api/connect.ts": $1,
    "./routes/api/send.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/AddRoom.tsx": $$0,
    "./islands/Chat.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
